name: DOCS Rendering
on:
  push:
    branches: [main, devel]
jobs:
  compiler:
    name: Compiler
    runs-on: ubuntu-latest
    steps:
      - name: Checkout DOCS Repository
        uses: actions/checkout@v4
      - name: Compile LaTeX Source Code
        uses: xu-cheng/latex-action@v3
        with: 
          root_file: main.tex
          latexmk_use_xelatex: true
          continue_on_error: false
          extra_fonts: ./fonts/
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Renderings
          path: ./
          retention-days: 90
          compression-level: 0
          overwrite: false

          

